# Lab 1 - Numpy 

In [ ]:
import numpy as np

### Question 1

In [2]:
a=np.array([0, 1, 2, 3, 4, 5, 6, 7, 8])
np.reshape(a,(3,3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

### Question 2

In [3]:
a[a % 2 == 1] = -1
a

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8])

### Question 3

In [4]:
x = np.array([21, 64, 86, 22, 74, 55, 81, 79, 90, 89]) 
y = np.array([21, 7, 3, 45, 10, 29, 55, 4, 37, 18])

print(np.where(x > y))
print(np.where(x == y))

(array([1, 2, 4, 5, 6, 7, 8, 9]),)
(array([0]),)


### Question 4

In [5]:
m=np.arange(100).reshape(5,-1)
m[:,:4]

array([[ 0,  1,  2,  3],
       [20, 21, 22, 23],
       [40, 41, 42, 43],
       [60, 61, 62, 63],
       [80, 81, 82, 83]])

# Additional Questions

### Question 1

In [7]:
np.random.randint(30,41,size=10)

array([36, 37, 34, 39, 32, 32, 37, 37, 35, 35])

### Question 2

In [9]:
matA= np.array ([[1, 2, 3], [4, 5, 6], [7, 8, 10]])
matB= np.array ([[7, 8, 10] ,[4, 5, 6], [1, 2, 3]])

matC=matA+matB
print(matC)
print()
matE = matA-matB
print(matE)


[[ 8 10 13]
 [ 8 10 12]
 [ 8 10 13]]

[[-6 -6 -7]
 [ 0  0  0]
 [ 6  6  7]]


In [10]:
print("Sum of all elements in matrix A:",np.sum(a))
print("SUm of all column in matrix B:",matB.sum(axis=0))
print("Sum of all rows in matrix C:",matC.sum(axis=1))

Sum of all elements in matrix A: 16
SUm of all column in matrix B: [12 15 19]
Sum of all rows in matrix C: [31 30 31]


In [11]:
matD=matA*matB
matD

array([[ 7, 16, 30],
       [16, 25, 36],
       [ 7, 16, 30]])

In [12]:
matE=np.sort(matC,axis=1)
matE

array([[ 8, 10, 13],
       [ 8, 10, 12],
       [ 8, 10, 13]])

In [13]:
matE.transpose()

array([[ 8,  8,  8],
       [10, 10, 10],
       [13, 12, 13]])