In [1]:
import torch
import numpy as np

In [2]:
tensor = torch.arange(1, 17).reshape(4, 4)

reshaped = tensor.reshape(2, 8)
viewed = tensor.view(2, 8)
stacked = torch.stack((tensor, tensor), dim=0)
squeezed = tensor.unsqueeze(0).squeeze()
unsqueezed = tensor.unsqueeze(0)

print("Original Tensor:\n", tensor)
print("\nReshaped Tensor:\n", reshaped)
print("\nViewed Tensor:\n", viewed)
print("\nStacked Tensor:\n", stacked)
print("\nSqueezed Tensor:\n", squeezed)
print("\nUnsqueezed Tensor:\n", unsqueezed)

Original Tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Reshaped Tensor:
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]])

Viewed Tensor:
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
        [ 9, 10, 11, 12, 13, 14, 15, 16]])

Stacked Tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]],

        [[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])

Squeezed Tensor:
 tensor([[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12],
        [13, 14, 15, 16]])

Unsqueezed Tensor:
 tensor([[[ 1,  2,  3,  4],
         [ 5,  6,  7,  8],
         [ 9, 10, 11, 12],
         [13, 14, 15, 16]]])


In [3]:
permuted = tensor.permute(1, 0)
print("Permuted Tensor:", permuted)

Permuted Tensor: tensor([[ 1,  5,  9, 13],
        [ 2,  6, 10, 14],
        [ 3,  7, 11, 15],
        [ 4,  8, 12, 16]])


In [4]:
indexed = tensor[0, 1] 
row = tensor[1]         
col = tensor[:, 2]      

print("Indexed Element:", indexed)
print("Row:", row)
print("Column:", col)

Indexed Element: tensor(2)
Row: tensor([5, 6, 7, 8])
Column: tensor([ 3,  7, 11, 15])


In [5]:
numpy_array = np.array([1, 2, 3])
tensor_from_numpy = torch.from_numpy(numpy_array)

numpy_from_tensor = tensor_from_numpy.numpy()

print("NumPy Array:", numpy_array)
print("Tensor from NumPy:", tensor_from_numpy)
print("NumPy from Tensor:", numpy_from_tensor)

NumPy Array: [1 2 3]
Tensor from NumPy: tensor([1, 2, 3])
NumPy from Tensor: [1 2 3]


In [6]:
random_tensor = torch.rand(7, 7)
print("Random Tensor:", random_tensor)

Random Tensor: tensor([[0.0928, 0.2787, 0.0177, 0.5718, 0.6479, 0.6901, 0.9447],
        [0.7362, 0.0760, 0.9100, 0.3260, 0.6650, 0.6047, 0.1548],
        [0.3910, 0.6988, 0.7486, 0.9873, 0.4095, 0.4843, 0.3843],
        [0.8369, 0.4518, 0.6913, 0.9423, 0.5078, 0.5942, 0.4944],
        [0.4591, 0.8336, 0.1157, 0.0501, 0.9595, 0.9439, 0.4257],
        [0.1791, 0.3779, 0.1751, 0.3254, 0.1319, 0.2509, 0.6034],
        [0.4898, 0.4924, 0.5131, 0.0672, 0.8044, 0.1328, 0.3356]])


In [7]:
tensor_a = random_tensor
tensor_b = torch.rand(1, 7).T  

result = torch.matmul(tensor_a, tensor_b)
print("Matrix Multiplication Result:", result)

Matrix Multiplication Result: tensor([[2.1117],
        [2.5929],
        [2.3468],
        [2.7183],
        [2.5394],
        [1.1021],
        [1.8749]])


In [8]:
device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

tensor1 = torch.rand(2, 3).to(device)
tensor2 = torch.rand(2, 3).to(device)

print("Tensor1 on GPU:", tensor1)
print("Tensor2 on GPU:", tensor2)

Tensor1 on GPU: tensor([[0.8439, 0.2841, 0.8534],
        [0.0202, 0.8881, 0.4408]])
Tensor2 on GPU: tensor([[0.1657, 0.3516, 0.7146],
        [0.6101, 0.6235, 0.0638]])


/home/student/Documents/220962436_Keshav/dllab/lib/python3.12/site-packages/torch/cuda/__init__.py:129: UserWarning: CUDA initialization: The NVIDIA driver on your system is too old (found version 11040). Please update your GPU driver by downloading and installing a new version from the URL: http://www.nvidia.com/Download/index.aspx Alternatively, go to: https://pytorch.org to install a PyTorch version that has been compiled with your version of the CUDA driver. (Triggered internally at ../c10/cuda/CUDAFunctions.cpp:108.)
  return torch._C._cuda_getDeviceCount() > 0


In [9]:
tensor1 = tensor1.T 

result_gpu = torch.matmul(tensor1, tensor2)  
print("Matrix Multiplication on GPU:", result_gpu)

Matrix Multiplication on GPU: tensor([[0.1521, 0.3093, 0.6043],
        [0.5890, 0.6536, 0.2597],
        [0.4103, 0.5749, 0.6380]])


In [10]:
max_value = result_gpu.max()
min_value = result_gpu.min()

print("Max Value:", max_value)
print("Min Value:", min_value)

Max Value: tensor(0.6536)
Min Value: tensor(0.1521)


In [11]:
max_index = result_gpu.argmax()
min_index = result_gpu.argmin()

print("Max Index:", max_index)
print("Min Index:", min_index)

Max Index: tensor(4)
Min Index: tensor(0)


In [12]:
torch.manual_seed(7)

tensor3 = torch.rand(1, 1, 1, 10)

reshaped_tensor = tensor3.squeeze()

print("Original Tensor Shape:", tensor3.shape)
print("Reshaped Tensor Shape:", reshaped_tensor.shape)
print("Original Tensor:", tensor3)
print("Reshaped Tensor:", reshaped_tensor)

Original Tensor Shape: torch.Size([1, 1, 1, 10])
Reshaped Tensor Shape: torch.Size([10])
Original Tensor: tensor([[[[0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297,
           0.3653, 0.8513]]]])
Reshaped Tensor: tensor([0.5349, 0.1988, 0.6592, 0.6569, 0.2328, 0.4251, 0.2071, 0.6297, 0.3653,
        0.8513])
